/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkedinReviewRouteImport } from './routes/linkedin-review'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LinkedinReviewResultsRouteImport } from './routes/linkedin-review.results'
import { Route as EmployerSignupRouteImport } from './routes/employer.signup'
import { Route as EmployerLoginRouteImport } from './routes/employer.login'
import { Route as EmployerDashboardRouteImport } from './routes/employer.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinReviewRoute = LinkedinReviewRouteImport.update({
  id: '/linkedin-review',
  path: '/linkedin-review',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinReviewResultsRoute = LinkedinReviewResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LinkedinReviewRoute,
} as any)
const EmployerSignupRoute = EmployerSignupRouteImport.update({
  id: '/employer/signup',
  path: '/employer/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerLoginRoute = EmployerLoginRouteImport.update({
  id: '/employer/login',
  path: '/employer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/linkedin-review': typeof LinkedinReviewRouteWithChildren
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/login': typeof EmployerLoginRoute
  '/employer/signup': typeof EmployerSignupRoute
  '/linkedin-review/results': typeof LinkedinReviewResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/linkedin-review': typeof LinkedinReviewRouteWithChildren
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/login': typeof EmployerLoginRoute
  '/employer/signup': typeof EmployerSignupRoute
  '/linkedin-review/results': typeof LinkedinReviewResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/linkedin-review': typeof LinkedinReviewRouteWithChildren
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/login': typeof EmployerLoginRoute
  '/employer/signup': typeof EmployerSignupRoute
  '/linkedin-review/results': typeof LinkedinReviewResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/linkedin-review'
    | '/login'
    | '/results'
    | '/signup'
    | '/employer/dashboard'
    | '/employer/login'
    | '/employer/signup'
    | '/linkedin-review/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/linkedin-review'
    | '/login'
    | '/results'
    | '/signup'
    | '/employer/dashboard'
    | '/employer/login'
    | '/employer/signup'
    | '/linkedin-review/results'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/linkedin-review'
    | '/login'
    | '/results'
    | '/signup'
    | '/employer/dashboard'
    | '/employer/login'
    | '/employer/signup'
    | '/linkedin-review/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  DashboardRoute: typeof DashboardRoute
  LinkedinReviewRoute: typeof LinkedinReviewRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResultsRoute: typeof ResultsRoute
  SignupRoute: typeof SignupRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerLoginRoute: typeof EmployerLoginRoute
  EmployerSignupRoute: typeof EmployerSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-review': {
      id: '/linkedin-review'
      path: '/linkedin-review'
      fullPath: '/linkedin-review'
      preLoaderRoute: typeof LinkedinReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-review/results': {
      id: '/linkedin-review/results'
      path: '/results'
      fullPath: '/linkedin-review/results'
      preLoaderRoute: typeof LinkedinReviewResultsRouteImport
      parentRoute: typeof LinkedinReviewRoute
    }
    '/employer/signup': {
      id: '/employer/signup'
      path: '/employer/signup'
      fullPath: '/employer/signup'
      preLoaderRoute: typeof EmployerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/login': {
      id: '/employer/login'
      path: '/employer/login'
      fullPath: '/employer/login'
      preLoaderRoute: typeof EmployerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LinkedinReviewRouteChildren {
  LinkedinReviewResultsRoute: typeof LinkedinReviewResultsRoute
}

const LinkedinReviewRouteChildren: LinkedinReviewRouteChildren = {
  LinkedinReviewResultsRoute: LinkedinReviewResultsRoute,
}

const LinkedinReviewRouteWithChildren = LinkedinReviewRoute._addFileChildren(
  LinkedinReviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  DashboardRoute: DashboardRoute,
  LinkedinReviewRoute: LinkedinReviewRouteWithChildren,
  LoginRoute: LoginRoute,
  ResultsRoute: ResultsRoute,
  SignupRoute: SignupRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerLoginRoute: EmployerLoginRoute,
  EmployerSignupRoute: EmployerSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
